/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprimeiroapp;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame implements ListSelectionListener {
    
    private ArrayList<Pessoa> listaDePessoas = new ArrayList<>();
    private DefaultTableModel modeloDadosTabela;
    private Pessoa pessoa;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        limpaCampos();
        inicializaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCadastro = new javax.swing.JTable();
        btDeletar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 0, 0));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel7.setText("Código");
        jPanel2.add(jLabel7);

        tfCodigo.setEditable(false);
        tfCodigo.setBackground(new java.awt.Color(51, 51, 51));
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setFocusable(false);
        tfCodigo.setName(""); // NOI18N
        jPanel2.add(tfCodigo);

        jLabel5.setText("Nome");
        jPanel2.add(jLabel5);
        jPanel2.add(tfNome);

        jLabel4.setText("Telefone");
        jPanel2.add(jLabel4);
        jPanel2.add(tfTelefone);

        jLabel6.setText("Endereço");
        jPanel2.add(jLabel6);
        jPanel2.add(tfEndereco);

        tbCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Telefone", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCadastro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbCadastro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbCadastro);

        btDeletar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(51, 51, 255));
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConsultar)
                        .addGap(63, 63, 63)
                        .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar)
                        .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (validaTela()) {
            if (pessoa == null) {
                ControlePessoas.salvaPessoa(tfCodigo.getText(),
                        tfNome.getText(),
                        tfEndereco.getText(),
                        tfTelefone.getText(),
                        listaDePessoas,
                        modeloDadosTabela
                );
            } else {
                ControlePessoas.atualizaPessoa(tfCodigo.getText(),
                        tfNome.getText(),
                        tfEndereco.getText(),
                        tfTelefone.getText(),
                        modeloDadosTabela,
                        pessoa, listaDePessoas.indexOf(pessoa)
                );
            }
            limpaCampos();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        
        int posicaoSelecionada = tbCadastro.getSelectedRow();
        if (posicaoSelecionada != -1) {
            ControlePessoas.excluiPessoa(posicaoSelecionada, listaDePessoas, modeloDadosTabela);
            geraNovoCodigo();
            limpaCampos();
        }

    }//GEN-LAST:event_btDeletarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        String nomeFiltro = tfNome.getText();
        nomeFiltro = nomeFiltro.trim();
        if (!nomeFiltro.isBlank()) {
//            for(int i = 0; i < listaDePessoas.size(); i++)
//            {
//                Pessoa pessoa = listaDePessoas.get(i);
//                if(pessoa.getNome().equals(nomeFiltro))
//                {
//                    trataPessoaEncontrada(pessoa);
//                    break;
//                }
//            }
            boolean encontrouPessoa = false;
            for (Pessoa pessoa : listaDePessoas) {
                //Comparação transformando tudo em maiusculo
//                if (pessoa.getNome().toUpperCase().equals(nomeFiltro.toUpperCase())) {
//                    trataPessoaEncontrada(pessoa);
//                    break;
//                }
                //Comparação utilizando método específico de comparação que ignora o case
//                if (pessoa.getNome().equalsIgnoreCase(nomeFiltro)) {
//                    trataPessoaEncontrada(pessoa);
//                    break;
//                }

               if (pessoa.getNome().toUpperCase().contains(nomeFiltro.toUpperCase())) 
               {
                    trataPessoaEncontrada(pessoa);
                    encontrouPessoa = true;
                    break;
                }
            }
            if(!encontrouPessoa)
                limpaCampos();
            

//                listaPessoas tem 3 de tamanho
//                listaPessoas[0] = Pessoa(1, "Rafael" ...)
//                listaPessoas[1] = Pessoa(2, "Murilo" ...)
//                listaPessoas[2] = Pessoa(3, "Lucas" ...)
//                listaDePessoas.indexOf(new Pessoa(3));
            // Suposta implementação do método indexOf
            // Retorna a posição (indice) da lista de um determinado objeto
            // A comparação é feita sempre utilizando o método equals que toda
            // classe possui
//                private int indexOf(Pessoa parametro)
//                {
//                    for(int = 0; i < listaDePessoas.size() ; i++)
//                    {
//                        if(listaDePessoas.get(i).equals(parametro))
//                            return i;
//                    }
//                }
//                listaPessoas tem 3 de tamanho
//                listaPessoas[0] = Pessoa(1, "Rafael" ...)
//                listaPessoas[1] = Pessoa(2, "Murilo" ...)
//                listaPessoas[2] = Pessoa(3, "Lucas" ...)
//                listaDePessoas.indexOf(new Pessoa(3));
            // Suposta implementação do método indexOf
            // Retorna a posição (indice) da lista de um determinado objeto
            // A comparação é feita sempre utilizando o método equals que toda
            // classe possui
//                private int indexOf(Pessoa parametro)
//                {
//                    for(int = 0; i < listaDePessoas.size() ; i++)
//                    {
//                        if(listaDePessoas.get(i).equals(parametro))
//                            return i;
//                    }
//                }
            //                listaPessoas tem 3 de tamanho
//                listaPessoas[0] = Pessoa(1, "Rafael" ...)
//                listaPessoas[1] = Pessoa(2, "Murilo" ...)
//                listaPessoas[2] = Pessoa(3, "Lucas" ...)
//                listaDePessoas.indexOf(new Pessoa(3));
            // Suposta implementação do método indexOf
            // Retorna a posição (indice) da lista de um determinado objeto
            // A comparação é feita sempre utilizando o método equals que toda
            // classe possui
//                private int indexOf(Pessoa parametro)
//                {
//                    for(int = 0; i < listaDePessoas.size() ; i++)
//                    {
//                        if(listaDePessoas.get(i).equals(parametro))
//                            return i;
//                    }
//                }
            //Comparação de datas utilizando objetos da classe Date
            //SimpleDateFormat é uma classe utilizada para formatação/transformação
            //de string em date
            // Após convertido, o equals dos objetos do tipo Date comparam
            // dia, mes, ano, hora, minuto, segundo e milisegundos
//            Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse("16/02/1990");
//            Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse("16/02/1990");
//            if(date1.equals(date2))
        }
    }//GEN-LAST:event_btConsultarActionPerformed
    
    private void trataPessoaEncontrada(Pessoa pessoa) {
        this.pessoa = pessoa;
        tfNome.setText(pessoa.getNome());
        tfEndereco.setText(pessoa.getEndereco());
        tfCodigo.setText(pessoa.getCodigo().toString());
        tfTelefone.setText(pessoa.getTelefone().toString());
    }

    private void limpaCampos() {
        geraNovoCodigo();
        tfNome.setText("");
        tfEndereco.setText("");
        tfTelefone.setText("");
        pessoa = null;
        tbCadastro.getSelectionModel().clearSelection();
    }
    
    private void geraNovoCodigo() {
        Integer proximoCodigo = ControlePessoas.getProximoCodigo(listaDePessoas);
        tfCodigo.setText(proximoCodigo.toString());
    }
    
    private void inicializaTabela() {
        modeloDadosTabela = (DefaultTableModel) tbCadastro.getModel();
        tbCadastro.getSelectionModel().addListSelectionListener(this);
    }
    
    @Override
    public void valueChanged(ListSelectionEvent e) {
        onSelecaoAlterada();
    }
    
    private void onSelecaoAlterada() {
        int posicaoSelecionada = tbCadastro.getSelectedRow();
        if (posicaoSelecionada >= 0) {
            pessoa = listaDePessoas.get(posicaoSelecionada);
            carregaValoresPessoa(pessoa);
        }
    }
    
    private void carregaValoresPessoa(Pessoa pessoa) {
        tfCodigo.setText(pessoa.getCodigo().toString());
        tfNome.setText(pessoa.getNome());
        tfTelefone.setText(pessoa.getTelefone());
        tfEndereco.setText(pessoa.getEndereco());
    }
    
    private boolean validaTela() {
        if (tfCodigo.getText().length() <= 0
                || !ControlePessoas.isCodigoValido(Integer.valueOf(tfCodigo.getText()))) {
            exibeMensagemConfirmacao("Código inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isNomeValido(tfNome.getText())) {
            exibeMensagemConfirmacao("Nome inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isTelefoneValido(tfTelefone.getText())) {
            exibeMensagemConfirmacao("Telefone inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isEnderecoValido((tfEndereco.getText()))) {
            exibeMensagemConfirmacao("Endereço inválido", "Validação");
            return false;
        }
        
        return true;
    }
    
    private void exibeMensagemConfirmacao(String mensagem, String titulo) {
        JOptionPane.showConfirmDialog(
                this,
                mensagem,
                titulo,
                JOptionPane.CLOSED_OPTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbCadastro;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    public enum TipoMensagem {
        TIPO_MENSAGEM_OK,
        TIPO_MENSAGEM_SIM_NAO;
    }
    
    public void exibeMensagem(TipoMensagem tipoMensagem) {
        switch (tipoMensagem) {
            case TIPO_MENSAGEM_OK:
                break;
            case TIPO_MENSAGEM_SIM_NAO:
                break;
        }
    }
    
    public static final int TIPO_MENSAGEM_OK = 1;
    public static final int TIPO_MENSAGEM_SIM_NAO = 2;
    
    public void exibeMensagem(int tipoMensagem) {
        switch (tipoMensagem) {
            case TIPO_MENSAGEM_OK:
                break;
            case TIPO_MENSAGEM_SIM_NAO:
                break;
        }
    }
    
    public void teste() {
        exibeMensagem(3);
        exibeMensagem(2);
        exibeMensagem(TelaPrincipal.TIPO_MENSAGEM_OK);
        exibeMensagem(TelaPrincipal.TIPO_MENSAGEM_SIM_NAO);
        exibeMensagem(TipoMensagem.TIPO_MENSAGEM_SIM_NAO);
    }
}
