/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprimeiroapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ArrayList<Pessoa> listaDePessoas = new ArrayList<>();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        limpaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 0, 0));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel7.setText("Código");
        jPanel2.add(jLabel7);

        tfCodigo.setEditable(false);
        tfCodigo.setBackground(new java.awt.Color(51, 51, 51));
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setFocusable(false);
        tfCodigo.setName(""); // NOI18N
        jPanel2.add(tfCodigo);

        jLabel5.setText("Nome");
        jPanel2.add(jLabel5);

        tfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeFocusLost(evt);
            }
        });
        jPanel2.add(tfNome);

        jLabel4.setText("Telefone");
        jPanel2.add(jLabel4);
        jPanel2.add(tfTelefone);

        jLabel6.setText("Endereço");
        jPanel2.add(jLabel6);
        jPanel2.add(tfEndereco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(352, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (validaTela()) {
            ControlePessoas.salvaPessoa(
                    tfCodigo.getText(),
                     tfNome.getText(),
                     tfEndereco.getText(),
                     tfTelefone.getText(),
                     listaDePessoas
            );
            limpaCampos();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusLost
        if (!ControlePessoas.isNomeValido(tfNome.getText())) {
            exibeMensagemConfirmacao("Nome inválido", "Validação");
            tfNome.requestFocus();
        }
    }//GEN-LAST:event_tfNomeFocusLost

    void limpaCampos() {
        Integer proximoCodigo = ControlePessoas.getProximoCodigo(listaDePessoas);
        tfCodigo.setText(proximoCodigo.toString());
        tfNome.setText("");
        tfEndereco.setText("");
        tfTelefone.setText("");
    }

    boolean validaTela() {
        if (tfCodigo.getText().length() <= 0
                || !ControlePessoas.isCodigoValido(Integer.valueOf(tfCodigo.getText()))) {
            exibeMensagemConfirmacao("Código inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isNomeValido(tfNome.getText())) {
            exibeMensagemConfirmacao("Nome inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isTelefoneValido(tfTelefone.getText())) {
            exibeMensagemConfirmacao("Telefone inválido", "Validação");
            return false;
        }
        if (!ControlePessoas.isEnderecoValido((tfEndereco.getText()))) {
            exibeMensagemConfirmacao("Endereço inválido", "Validação");
            return false;
        }

        return true;
    }

    void exibeMensagemConfirmacao(String mensagem, String titulo) {
        JOptionPane.showConfirmDialog(
                this,
                mensagem,
                titulo,
                JOptionPane.CLOSED_OPTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
